#ifndef OS64_SURFACE_TYPES_H
#define OS64_SURFACE_TYPES_H

#include <stdint.h>

#include "os64/handle_types.h"

#define OS64_SURFACE_ABI_VERSION 1u

#define OS_SURFACE_MAP_READ  0x00000001u
#define OS_SURFACE_MAP_WRITE 0x00000002u
#define OS_SURFACE_MAP_VALID_MASK (OS_SURFACE_MAP_READ | OS_SURFACE_MAP_WRITE)

#define OS_SURFACE_APPLICATION_RIGHTS \
    (OS_HANDLE_RIGHT_READ | OS_HANDLE_RIGHT_WRITE | OS_HANDLE_RIGHT_MAP | OS_HANDLE_RIGHT_TRANSFER)
#define OS_SURFACE_TRANSFER_RIGHTS \
    (OS_HANDLE_RIGHT_READ | OS_HANDLE_RIGHT_MAP)

#endif
