#!/usr/bin/env python3
import argparse
import json
from pathlib import Path

from driver_policy import validate_policy


KIND_CONSTANTS = {
    "block": "DRIVER_KIND_BLOCK", "bus": "DRIVER_KIND_BUS",
    "display": "DRIVER_KIND_DISPLAY", "fs": "DRIVER_KIND_FS",
    "input": "DRIVER_KIND_INPUT", "timer": "DRIVER_KIND_TIMER",
    "demo": "DRIVER_KIND_MODULE",
}
PERMISSION_CONSTANTS = {
    "PCI": "DRV_PERMISSION_PCI", "MMIO": "DRV_PERMISSION_MMIO",
    "INTERRUPT": "DRV_PERMISSION_INTERRUPT", "BLOCK": "DRV_PERMISSION_BLOCK",
    "VFS": "DRV_PERMISSION_VFS", "INPUT": "DRV_PERMISSION_INPUT",
    "TIMER": "DRV_PERMISSION_TIMER", "DISPLAY": "DRV_PERMISSION_DISPLAY",
}
STATE_CONSTANTS = {
    "registered": "DRIVER_STATE_REGISTERED", "ready": "DRIVER_STATE_READY",
    "failed": "DRIVER_STATE_FAILED",
    "gop_ready": "gop.ready() ? DRIVER_STATE_READY : DRIVER_STATE_FAILED",
}
STAGES = ("boot", "kernel", "runtime")


def cpp_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def load(root: Path):
    errors = validate_policy(root)
    if errors:
        raise SystemExit("driver policy validation failed:\n- " + "\n- ".join(errors))
    policy = json.loads((root / "config/drivers.json").read_text(encoding="utf-8"))
    result = []
    for entry in policy["drivers"]:
        settings_path = root / "drivers" / entry["path"] / "settings.json"
        settings = json.loads(settings_path.read_text(encoding="utf-8"))
        result.append((entry, settings, settings_path))
    return result


def linked_objects(settings: dict, path: Path) -> list[str]:
    linked = settings.get("linked", {})
    objects = linked.get("objects")
    if not isinstance(objects, list) or not objects:
        raise SystemExit(f"{path}: linked.objects must contain at least one root-relative object")
    return objects


def dependency_order(items):
    by_name = {entry["name"]: (entry, settings, path) for entry, settings, path in items}
    result = []
    visited = set()

    def visit(item):
        entry, settings, _path = item
        if entry["name"] in visited:
            return
        for dependency in settings.get("dependencies", []):
            if dependency in by_name:
                visit(by_name[dependency])
        visited.add(entry["name"])
        result.append(item)

    for item in items:
        visit(item)
    return result


def emit_make(root: Path, drivers) -> str:
    enabled = dependency_order([(e, s, p) for e, s, p in drivers if e["enabled"]])
    linked = [(e, s, p) for e, s, p in enabled if e["artifact"] == "linked"]
    packaged = [(e, s, p) for e, s, p in enabled if e["artifact"] == "drv"]
    lines = ["# Generated by tools/gen_driver_build.py. Do not edit."]
    lines.append("ENABLED_DRIVER_DIRS := " + " ".join("./drivers/" + e["path"] for e, _, _ in enabled))
    lines.append("LINKED_DRIVER_OBJECTS := " + " ".join(obj for _, s, p in linked for obj in linked_objects(s, p)))
    lines.append("DRIVER_PACKAGES := " + " ".join("./bin/" + e["name"] + ".drv" for e, _, _ in packaged))
    for stage in STAGES:
        names = ["./bin/" + e["name"] + ".drv" for e, _, _ in packaged if e["load_stage"] == stage]
        lines.append(f"{stage.upper()}_DRIVER_PACKAGES := " + " ".join(names))
    manual = ["./bin/" + e["name"] + ".drv" for e, _, _ in packaged if e["load_policy"] == "manual"]
    lines.append("MANUAL_DRIVER_PACKAGES := " + " ".join(manual))
    lines.append("")
    for entry, _settings, settings_path in packaged:
        driver_dir = "./drivers/" + entry["path"]
        sources = sorted(list(settings_path.parent.glob("*.c")) + list(settings_path.parent.glob("*.cpp")) +
                         list((settings_path.parent / "src").glob("*.c")) + list((settings_path.parent / "src").glob("*.cpp")))
        deps = " ".join("./" + str(path.relative_to(root)).replace("\\", "/") for path in sources)
        target = "./bin/" + entry["name"] + ".drv"
        lines.extend([
            f"{target}: ./config/drivers.json ./{settings_path.relative_to(root).as_posix()} {deps} ./tools/driver_project.py",
            f"\t$(MAKE) -C {driver_dir} package",
            "",
        ])
    return "\n".join(lines)


def permission_expr(values: list[str]) -> str:
    return " | ".join(PERMISSION_CONSTANTS[value] for value in values) if values else "0"


def emit_registry(drivers) -> str:
    linked = [(e, s, p) for e, s, p in drivers if e["enabled"] and e["artifact"] == "linked"]
    includes = {"kernel/driver/driver_manager.h", "kernel/driver/drv_format.h"}
    externs = set()
    for _, settings, _ in linked:
        includes.update(settings["linked"]["includes"])
        externs.update(settings["linked"]["externs"])
    lines = ["// Generated by tools/gen_driver_build.py from config/drivers.json.", ""]
    lines += [f"#include {cpp_string(value)}" for value in sorted(includes)]
    lines.append("")
    lines += sorted(externs)
    lines += [
        "", "static void activate_linked(const char* name, uint32_t kind,",
        "                            uint32_t permissions, void* instance, uint32_t state) {",
        "    if (driver_manager_register_builtin(name, \"linked\", kind, permissions, instance) == DRIVER_LOAD_OK) {",
        "        driver_manager_set_state(name, state);", "    }", "}", "",
    ]
    for stage in STAGES:
        lines.append(f"void driver_manager_activate_linked_{stage}() {{")
        selected = [(e, s, p) for e, s, p in linked if e["load_stage"] == stage]
        selected.sort(key=lambda item: (item[1]["linked"]["priority"], item[0]["name"]))
        for entry, settings, _ in selected:
            linked_data = settings["linked"]
            state = STATE_CONSTANTS[linked_data["state"]]
            lines.append(f"    activate_linked({cpp_string(entry['name'])}, {KIND_CONSTANTS[settings['domain']]},")
            lines.append(f"                    {permission_expr(settings['permissions'])}, {linked_data['instance']}, {state});")
        lines += ["}", ""]
    return "\n".join(lines)


def emit_activation(drivers) -> str:
    packaged = dependency_order([(e, s, p) for e, s, p in drivers if e["enabled"] and e["artifact"] == "drv"])
    boot = [e for e, _, _ in packaged if e["load_stage"] == "boot" and e["load_policy"] == "automatic"]
    automatic_paths = [e for e, _, _ in packaged if e["load_stage"] in ("kernel", "runtime") and e["load_policy"] == "automatic"]
    lines = [
        "// Generated by tools/gen_driver_build.py from config/drivers.json.",
        '#include "kernel/boot_info.h"', '#include "kernel/driver/driver_manager.h"', "",
    ]
    if boot:
        lines += [
            "static int same_name(const char* left, const char* right) {",
            "    uint32_t i = 0; while (left[i] != 0 && left[i] == right[i]) i++;",
            "    return left[i] == 0 && right[i] == 0;", "}", "",
        ]
    if automatic_paths:
        lines += [
            "static uint32_t activate_paths(const char* const* paths, uint32_t count) {",
            "    uint32_t loaded = 0;", "    for (uint32_t i = 0; i < count; i++) {",
            "        if (driver_manager_load_from_path(paths[i], 1) == DRIVER_LOAD_OK) loaded++;",
            "    }", "    return loaded;", "}", "",
        ]
    if boot:
        lines += ["static const char* const g_boot_driver_names[] = {"]
        lines += [f"    {cpp_string(e['name'])}," for e in boot]
        lines += ["};", ""]
    lines += [
        "uint32_t driver_manager_activate_packaged_boot(const BootInfo* boot_info) {",
        "    if (boot_info == 0 || boot_info->size < sizeof(BootInfo) ||",
        "        boot_info->boot_module_count > BOOT_MODULE_MAX ||",
        "        boot_info->boot_module_entry_size != sizeof(BootModule)) return 0;",
        "    uint32_t loaded = 0;", "    for (uint32_t i = 0; i < boot_info->boot_module_count; i++) {",
        "        const BootModule* module = &boot_info->boot_modules[i];",
        "        if (module->type != BOOT_MODULE_DRIVER || module->address == 0 ||",
        "            module->size == 0 || module->size > BOOT_DRIVER_MAX_SIZE) continue;",
    ]
    if boot:
        lines += [
            "        int selected = 0;",
            "        for (uint32_t j = 0; j < sizeof(g_boot_driver_names) / sizeof(g_boot_driver_names[0]); j++)",
            "            if (same_name(module->name, g_boot_driver_names[j])) selected = 1;",
            "        if (!selected) continue;",
            "        if (driver_manager_load_drv_image((const uint8_t*)(uintptr_t)module->address, module->size) == DRIVER_LOAD_OK) loaded++;",
        ]
    lines += ["    }", "    return loaded;", "}", ""]
    for stage in ("kernel", "runtime"):
        selected = [e for e, _, _ in packaged if e["load_stage"] == stage and e["load_policy"] == "automatic"]
        array = f"g_{stage}_driver_paths"
        if selected:
            lines.append(f"static const char* const {array}[] = {{")
            lines += [f"    {cpp_string('/' + e['name'] + '.drv')}," for e in selected]
            lines += ["};", ""]
            lines.append(f"uint32_t driver_manager_activate_packaged_{stage}() {{")
            lines.append(f"    return activate_paths({array}, sizeof({array}) / sizeof({array}[0]));")
            lines.append("}")
        else:
            lines.append(f"uint32_t driver_manager_activate_packaged_{stage}() {{ return 0; }}")
        lines.append("")
    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if not path.exists() or path.read_text(encoding="utf-8") != content:
        path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--root", type=Path, default=Path(__file__).resolve().parents[1])
    parser.add_argument("--make-output", type=Path)
    parser.add_argument("--registry-output", type=Path)
    parser.add_argument("--activation-output", type=Path)
    args = parser.parse_args()
    root = args.root.resolve()
    drivers = load(root)
    if not any((args.make_output, args.registry_output, args.activation_output)):
        raise SystemExit("at least one output is required")
    if args.make_output:
        write_if_changed(args.make_output, emit_make(root, drivers))
    if args.registry_output:
        write_if_changed(args.registry_output, emit_registry(drivers))
    if args.activation_output:
        write_if_changed(args.activation_output, emit_activation(drivers))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
