#!/usr/bin/env python3
import argparse
import json
from pathlib import Path


KIND_CONSTANTS = {
    "core": "DRIVER_KIND_CORE",
    "bus": "DRIVER_KIND_BUS",
    "block": "DRIVER_KIND_BLOCK",
    "input": "DRIVER_KIND_INPUT",
    "timer": "DRIVER_KIND_TIMER",
    "fs": "DRIVER_KIND_FS",
    "display": "DRIVER_KIND_DISPLAY",
    "module": "DRIVER_KIND_MODULE",
}

PERMISSION_CONSTANTS = {
    "PCI": "DRV_PERMISSION_PCI",
    "MMIO": "DRV_PERMISSION_MMIO",
    "INTERRUPT": "DRV_PERMISSION_INTERRUPT",
    "BLOCK": "DRV_PERMISSION_BLOCK",
    "VFS": "DRV_PERMISSION_VFS",
    "INPUT": "DRV_PERMISSION_INPUT",
    "TIMER": "DRV_PERMISSION_TIMER",
    "DISPLAY": "DRV_PERMISSION_DISPLAY",
}

STATE_CONSTANTS = {
    "registered": "DRIVER_STATE_REGISTERED",
    "ready": "DRIVER_STATE_READY",
    "failed": "DRIVER_STATE_FAILED",
    "gop_ready": "gop.ready() ? DRIVER_STATE_READY : DRIVER_STATE_FAILED",
}


def require_string(manifest: dict, key: str, path: Path) -> str:
    value = manifest.get(key)
    if not isinstance(value, str) or value == "":
        raise SystemExit(f"{path}: expected non-empty string field '{key}'")
    return value


def require_list(manifest: dict, key: str, path: Path) -> list:
    value = manifest.get(key, [])
    if not isinstance(value, list):
        raise SystemExit(f"{path}: expected list field '{key}'")
    return value


def cpp_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def permission_expr(values: list, path: Path) -> str:
    if not values:
        return "0"
    constants = []
    for value in values:
        if not isinstance(value, str) or value not in PERMISSION_CONSTANTS:
            raise SystemExit(f"{path}: unknown permission '{value}'")
        constants.append(PERMISSION_CONSTANTS[value])
    return " | ".join(constants)


def load_manifest(path: Path) -> dict:
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        raise SystemExit(f"{path}: invalid JSON: {exc}") from exc

    if manifest.get("link") != "builtin":
        raise SystemExit(f"{path}: builtin registry only accepts link=builtin")
    require_string(manifest, "name", path)
    require_string(manifest, "kind", path)
    require_string(manifest, "instance", path)
    if manifest["kind"] not in KIND_CONSTANTS:
        raise SystemExit(f"{path}: unknown driver kind '{manifest['kind']}'")
    state = manifest.get("state", "ready")
    if state not in STATE_CONSTANTS:
        raise SystemExit(f"{path}: unknown state '{state}'")
    return manifest


def emit_registry(manifests: list[tuple[Path, dict]]) -> str:
    includes = [
        "kernel/driver/driver_manager.h",
        "kernel/driver/drv_format.h",
    ]
    externs = []
    entries = []

    for path, manifest in manifests:
        includes.extend(require_list(manifest, "includes", path))
        externs.extend(require_list(manifest, "externs", path))
        entries.append((path, manifest))

    lines = [
        "// Generated by tools/gen_builtin_driver_registry.py.",
        "// Edit drivers/builtin/*/driver.json instead of this file.",
        "",
    ]
    for include in sorted(set(includes)):
        lines.append(f"#include {cpp_string(include)}")
    lines.append("")
    for extern in sorted(set(externs)):
        if not isinstance(extern, str) or not extern.startswith("extern "):
            raise SystemExit(f"invalid extern declaration: {extern!r}")
        lines.append(extern)
    lines.extend([
        "",
        "static void register_builtin_state(const char* name,",
        "                                   uint32_t kind,",
        "                                   uint32_t permissions,",
        "                                   void* instance,",
        "                                   uint32_t state) {",
        "    if (driver_manager_register_builtin(name, \"builtin\", kind, permissions, instance) == DRIVER_LOAD_OK) {",
        "        driver_manager_set_state(name, state);",
        "    }",
        "}",
        "",
        "void driver_manager_register_builtin_devices() {",
    ])

    for path, manifest in entries:
        if manifest.get("autoload", True) is False:
            continue
        name = require_string(manifest, "name", path)
        kind = KIND_CONSTANTS[manifest["kind"]]
        permissions = permission_expr(require_list(manifest, "permissions", path), path)
        instance = require_string(manifest, "instance", path)
        state = STATE_CONSTANTS[manifest.get("state", "ready")]
        lines.extend([
            f"    register_builtin_state({cpp_string(name)},",
            f"                           {kind},",
            f"                           {permissions},",
            f"                           {instance},",
            f"                           {state});",
        ])

    lines.extend(["}", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate OS64 builtin driver registry source.")
    parser.add_argument("--output", required=True, type=Path)
    parser.add_argument("manifests", nargs="+", type=Path)
    args = parser.parse_args()

    manifests = []
    for path in args.manifests:
        manifest = load_manifest(path)
        priority = manifest.get("priority", 1000)
        if not isinstance(priority, int):
            raise SystemExit(f"{path}: priority must be an integer")
        manifests.append((priority, path, manifest))

    manifests.sort(key=lambda item: (item[0], item[2]["name"]))
    output = emit_registry([(path, manifest) for _priority, path, manifest in manifests])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(output, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
